-- MySQL Script generated by MySQL Workbench
-- Fri Nov  1 11:23:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema student_meals_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `student_meals_db` ;

-- -----------------------------------------------------
-- Schema student_meals_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `student_meals_db` DEFAULT CHARACTER SET utf8 ;
USE `student_meals_db` ;

-- -----------------------------------------------------
-- Table `student_meals_db`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`students` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`students` (
  `student_no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `paid_until` DATE NULL,
  PRIMARY KEY (`student_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`meal_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`meal_request` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`meal_request` (
  `request_date` VARCHAR(45) NOT NULL,
  `holiday` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`request_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`allergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`allergies` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`allergies` (
  `allergy_id` INT NOT NULL AUTO_INCREMENT,
  `students_no` INT NOT NULL,
  `allergy` VARCHAR(45) NULL,
  PRIMARY KEY (`allergy_id`, `students_no`),
  INDEX `fk_allergies_students_idx` (`students_no` ASC) VISIBLE,
  CONSTRAINT `fk_allergies_students`
    FOREIGN KEY (`students_no`)
    REFERENCES `student_meals_db`.`students` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`dish` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`dish` (
  `dish_id` INT NOT NULL,
  `dish_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dish_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`students_has_meal_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`students_has_meal_request` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`students_has_meal_request` (
  `student_no` INT NOT NULL,
  `meal_request_date` VARCHAR(45) NOT NULL,
  `breakfast` VARCHAR(45) BINARY NULL,
  `lunch` VARCHAR(45) BINARY NULL,
  `dinner` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`student_no`, `meal_request_date`),
  INDEX `fk_students_has_meal_request_meal_request1_idx` (`meal_request_date` ASC) VISIBLE,
  INDEX `fk_students_has_meal_request_students1_idx` (`student_no` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_meal_request_students1`
    FOREIGN KEY (`student_no`)
    REFERENCES `student_meals_db`.`students` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_meal_request_meal_request1`
    FOREIGN KEY (`meal_request_date`)
    REFERENCES `student_meals_db`.`meal_request` (`request_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `student_meals_db`.`holiday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`holiday` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`holiday` (
  `holiday_id` INT NOT NULL,
  `holiday_date` DATE NOT NULL,
  `description` VARCHAR(90) NOT NULL,
  `holidaycol` VARCHAR(45) NULL,
  PRIMARY KEY (`holiday_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`dish_has_allergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`dish_has_allergies` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`dish_has_allergies` (
  `dish_id` INT NOT NULL,
  `allergy_id` INT NOT NULL,
  PRIMARY KEY (`dish_id`, `allergy_id`),
  INDEX `fk_dish_has_allergies_allergies1_idx` (`allergy_id` ASC) VISIBLE,
  INDEX `fk_dish_has_allergies_dish1_idx` (`dish_id` ASC) VISIBLE,
  CONSTRAINT `fk_dish_has_allergies_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `student_meals_db`.`dish` (`dish_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dish_has_allergies_allergies1`
    FOREIGN KEY (`allergy_id`)
    REFERENCES `student_meals_db`.`allergies` (`allergy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_meals_db`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_meals_db`.`payment` ;

CREATE TABLE IF NOT EXISTS `student_meals_db`.`payment` (
  `payment_id` INT NOT NULL,
  `student_name` INT NOT NULL,
  `payment` VARCHAR(45) NOT NULL,
  `payment_amt` INT NULL,
  `payment_date` VARCHAR(45) NULL,
  PRIMARY KEY (`payment_id`, `student_name`),
  INDEX `fk_past_payment_students1_idx` (`student_name` ASC) VISIBLE,
  CONSTRAINT `fk_past_payment_students1`
    FOREIGN KEY (`student_name`)
    REFERENCES `student_meals_db`.`students` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
